// ID identifying the cluster to create. Use your username so that resources created can be tracked back to you.
cluster_id = "ocp-cluster"

// Domain of the cluster. This should be "${cluster_id}.${base_domain}".
cluster_domain = "ocp-cluster.openshift.local"

// Base domain from which the cluster domain is a subdomain.
base_domain = "openshift.local"

// Name of the vSphere server. The dev cluster is on "vcsa.vmware.devcluster.openshift.com".
vsphere_server = "192.168.1.80"

// User on the vSphere server.
vsphere_user = "administrator@vsphere.local"

// Password of the user on the vSphere server.
vsphere_password = "VMware1!"

// Name of the vSphere cluster. The dev cluster is "devel".
vsphere_cluster = "Cluster"

// Name of the vSphere data center. The dev cluster is "dc1".
vsphere_datacenter = "Datacenter"

// Name of the vSphere data store to use for the VMs. The dev cluster uses "nvme-ds1".
vsphere_datastore = "OCP_DS1"

// Name of the VM template to clone to create VMs for the cluster. The dev cluster has a template named "rhcos-latest".
vm_template = "fcos-32.2"

//Set the vSphere network your VMs will be deployed to. 
vm_network = "VM Network" 

// The machine_cidr where IP addresses will be assigned for cluster nodes.
// Additionally, IPAM will assign IPs based on the network ID. 
// machine_cidr = "192.168.1.0/24"

// The number of control plane VMs to create. Default is 3.
control_plane_count = 3

// The number of compute VMs to create. Default is 3.
compute_count = 2

// URL of the bootstrap ignition. This needs to be publicly accessible so that the bootstrap machine can pull the ignition.
// bootstrap_ignition_url = "http://192.168.1.90:8080/append-bootstrap.ign"
bootstrap_ignition = <<END_OF_BOOTSTRAP_IGNITION
{"ignition":{"config":{"merge":[{"source":"http://192.168.1.90:8080/bootstrap.ign","verification":{}}],"replace":{"source":null,"verification":{}}},"security":{"tls":{}},"timeouts":{},"version":"3.0.0"},"passwd":{},"storage":{},"systemd":{}}
END_OF_BOOTSTRAP_IGNITION

// Ignition config for the control plane machines. You should copy the contents of the master.ign generated by the installer.
control_plane_ignition = <<END_OF_MASTER_IGNITION
{"ignition":{"config":{"merge":[{"source":"https://api-int.ocp-cluster.openshift.local:22623/config/master","verification":{}}],"replace":{"verification":{}}},"proxy":{},"security":{"tls":{"certificateAuthorities":[{"source":"data:text/plain;charset=utf-8;base64,LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFRENDQWZpZ0F3SUJBZ0lJQU5WZlgyYXQ2aWN3RFFZSktvWklodmNOQVFFTEJRQXdKakVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1SQXdEZ1lEVlFRREV3ZHliMjkwTFdOaE1CNFhEVEl3TURrd09ERTRNRGt6T0ZvWApEVE13TURrd05qRTRNRGt6T0Zvd0pqRVNNQkFHQTFVRUN4TUpiM0JsYm5Ob2FXWjBNUkF3RGdZRFZRUURFd2R5CmIyOTBMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUExbXZoSGpBN3BVWW8KRVpidWtWM0NBWHBaY3c5R0VxbExtdm1lOEZEczZlNDBoSW9uMG5WZ3NWUFYzRHdXOWRPUG9UV3lVbFduUWtZZQowd0tKREQvRzg0T0pPUDFMd2laQ0hNS3dYYmFRR2g4RmFWMWN0S24vazR2WHVHVWlCTVFsMmJsbnM2eG0wd2NZCjM1OVFSbmg5cEN6ZGY3ampuMnBSTHM2M0cwOVVlaHJnZEpQbFRKQWNEMHpwUVNoNFJUVFpCdVA5bWxNak9yakgKenR0SjV1UU9WMDNicTFJL3ZpbDh0emNnTWVLUHFBVWpPUTNUaXp3Tjlqc3kxeUVUeTJEVXZLamZjQWUyVVVjdgplUmdVU1l2ekg4amJLRFB6Vk55L3hkWVFPd1Rnd2M0VmdrQVNZcTVrMEU2Vmo4NTJsZXVXWnl3SDhUellEdlFPCnYwUVJEMXV3K1FJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBcVF3RHdZRFZSMFRBUUgvQkFVd0F3RUIKL3pBZEJnTlZIUTRFRmdRVUxpRExZM25FMnJJSWpCcnJ4VHkzSUpFb085OHdEUVlKS29aSWh2Y05BUUVMQlFBRApnZ0VCQURYeGxRVGFnZHJ2L3FtMkdMTEJGOGF2enpKYmltMkNDazA5MmcybHJlRVBmdGFZeWRXcTdPVzBXdGFsCllzTDRxdDV1bW5ackV5NTF5bElEcnBNc1ZKd0g2K1lBbDk2dkxidTd0dmhacjZhRHhpZkdDWWNpakhNWGRMOVIKTkRDS21FUXozRUJWdWhleDVnSFo4ZTJuR201OURrUnFQT0dEa1lZYWQvTDNlUGFHV0E2TkdxZXp1cDQ1UEc1Nwp3WTRweStMSlN5YVNyMUpqWC9PeTlWOXk1ck1jTTVUcTNsejZOWHdjUS92aEVxMFpPSnMwK1d6SXVvRTlKVC9OClpZSGU3VVc2enNKYTltdCt1cm41RlRhMUQveVJmem5JdWhIVFVmWHI0UWxWWklrMDZVWkk4bXVVV0xjZWlrRkYKY3BwN0ZUOWZhTWpKWUk5RGNXSm1ZZUlqVHZFPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==","verification":{}}]}},"timeouts":{},"version":"3.1.0"},"passwd":{},"storage":{},"systemd":{}}
END_OF_MASTER_IGNITION

// Ignition config for the compute machines. You should copy the contents of the worker.ign generated by the installer.
compute_ignition = <<END_OF_WORKER_IGNITION
{"ignition":{"config":{"merge":[{"source":"https://api-int.ocp-cluster.openshift.local:22623/config/worker","verification":{}}],"replace":{"verification":{}}},"proxy":{},"security":{"tls":{"certificateAuthorities":[{"source":"data:text/plain;charset=utf-8;base64,LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFRENDQWZpZ0F3SUJBZ0lJQU5WZlgyYXQ2aWN3RFFZSktvWklodmNOQVFFTEJRQXdKakVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1SQXdEZ1lEVlFRREV3ZHliMjkwTFdOaE1CNFhEVEl3TURrd09ERTRNRGt6T0ZvWApEVE13TURrd05qRTRNRGt6T0Zvd0pqRVNNQkFHQTFVRUN4TUpiM0JsYm5Ob2FXWjBNUkF3RGdZRFZRUURFd2R5CmIyOTBMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUExbXZoSGpBN3BVWW8KRVpidWtWM0NBWHBaY3c5R0VxbExtdm1lOEZEczZlNDBoSW9uMG5WZ3NWUFYzRHdXOWRPUG9UV3lVbFduUWtZZQowd0tKREQvRzg0T0pPUDFMd2laQ0hNS3dYYmFRR2g4RmFWMWN0S24vazR2WHVHVWlCTVFsMmJsbnM2eG0wd2NZCjM1OVFSbmg5cEN6ZGY3ampuMnBSTHM2M0cwOVVlaHJnZEpQbFRKQWNEMHpwUVNoNFJUVFpCdVA5bWxNak9yakgKenR0SjV1UU9WMDNicTFJL3ZpbDh0emNnTWVLUHFBVWpPUTNUaXp3Tjlqc3kxeUVUeTJEVXZLamZjQWUyVVVjdgplUmdVU1l2ekg4amJLRFB6Vk55L3hkWVFPd1Rnd2M0VmdrQVNZcTVrMEU2Vmo4NTJsZXVXWnl3SDhUellEdlFPCnYwUVJEMXV3K1FJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBcVF3RHdZRFZSMFRBUUgvQkFVd0F3RUIKL3pBZEJnTlZIUTRFRmdRVUxpRExZM25FMnJJSWpCcnJ4VHkzSUpFb085OHdEUVlKS29aSWh2Y05BUUVMQlFBRApnZ0VCQURYeGxRVGFnZHJ2L3FtMkdMTEJGOGF2enpKYmltMkNDazA5MmcybHJlRVBmdGFZeWRXcTdPVzBXdGFsCllzTDRxdDV1bW5ackV5NTF5bElEcnBNc1ZKd0g2K1lBbDk2dkxidTd0dmhacjZhRHhpZkdDWWNpakhNWGRMOVIKTkRDS21FUXozRUJWdWhleDVnSFo4ZTJuR201OURrUnFQT0dEa1lZYWQvTDNlUGFHV0E2TkdxZXp1cDQ1UEc1Nwp3WTRweStMSlN5YVNyMUpqWC9PeTlWOXk1ck1jTTVUcTNsejZOWHdjUS92aEVxMFpPSnMwK1d6SXVvRTlKVC9OClpZSGU3VVc2enNKYTltdCt1cm41RlRhMUQveVJmem5JdWhIVFVmWHI0UWxWWklrMDZVWkk4bXVVV0xjZWlrRkYKY3BwN0ZUOWZhTWpKWUk5RGNXSm1ZZUlqVHZFPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==","verification":{}}]}},"timeouts":{},"version":"3.1.0"},"passwd":{},"storage":{},"systemd":{}}
END_OF_WORKER_IGNITION

// Set ipam and ipam_token if you want to use the IPAM server to reserve IP
// addresses for the VMs.

// Address or hostname of the IPAM server from which to reserve IP addresses for the cluster machines.
// ipam = "139.178.89.254"

// Token to use to authenticate with the IPAM server.
// ipam_token = "TOKEN_FOR_THE_IPAM_SERVER"

// Set bootstrap_ip, control_plane_ip, and compute_ip if you want to use static
// IPs reserved someone else, rather than the IPAM server.

// The IP address to assign to the bootstrap VM.
// bootstrap_ip = "192.168.1.99"
bootstrap_mac = "00:50:56:93:00:01"

// The IP addresses to assign to the control plane VMs. The length of this list
// must match the value of control_plane_count.
// control_plane_ips = ["192.168.1.91", "192.168.1.92", "192.168.1.93"]
// control_plane_ips = ["192.168.1.91","192.168.1.92","192.168.1.93"]
control_plane_macs = ["00:50:56:93:00:02", "00:50:56:93:00:03", "00:50:56:93:00:04"]

// The IP addresses to assign to the compute VMs. The length of this list must
// match the value of compute_count.
// compute_ips = ["192.168.1.94", "192.168.1.95"]
// compute_ips = ["192.168.1.94","192.168.1.95"]
compute_macs = ["00:50:56:93:00:05", "00:50:56:93:00:06"]
